Name : Guizhi Xu

CWID : 20008770

email: gxu14@stevens.edu

In [140]:
# Import all the required libraries
import numpy as np
import pandas as pd
import operator

Read the Dataset using read_csv function from Pandas

In [141]:
## Read the dataset from the two files into ratings_data, movies_data and user_data
ratings_data = pd.read_table("ratings.dat", sep = "::", header = None, encoding = 'ISO-8859-1')
movies_data = pd.read_table("movies.dat", sep = "::", header = None, encoding = 'ISO-8859-1')
user_data = pd.read_table("users.dat", sep = "::", header = None, encoding = 'ISO-8859-1')

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


Use Numpy to create a ratings data matrix. Print the shape of the matrix

In [142]:
ratings_data = ratings_data.rename(columns={0: "user_id" , 1: "movie_id" , 2: "rating" , 3: "serialnumber" })
ratings_data.head()

user_id  movie_id  rating  serialnumber
0        1      1193       5     978300760
1        1       661       3     978302109
2        1       914       3     978301968
3        1      3408       4     978300275
4        1      2355       5     978824291

In [143]:
movies_data = movies_data.rename(columns = {0: "movie_id" , 1: "title" , 2: "genre"})
movies_data.head()

movie_id                               title                         genre
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [144]:
user_data = user_data.rename(columns={0: "user_id" , 1: "gender" , 2: "age" , 3: "characteristiccode" , 4: "address"})
user_data.head()

user_id gender  age  characteristiccode address
0        1      F    1                  10   48067
1        2      M   56                  16   70072
2        3      M   25                  15   55117
3        4      M   45                   7   02460
4        5      M   25                  20   55455

In [145]:
ratings_mat = np.ndarray(shape=(np.max(ratings_data.movie_id.values), np.max(ratings_data.user_id.values)),dtype=np.uint8)
ratings_mat[ratings_data.movie_id.values - 1, ratings_data.user_id.values - 1] = ratings_data.rating.values
ratings_mat


array([[ 5,  0,  0, ...,  0,  0,  3],
       [ 9,  0,  0, ...,  0,  0,  0],
       [15,  0,  0, ...,  0,  0,  0],
       ...,
       [ 5,  0,  0, ...,  0,  0,  0],
       [ 5,  0,  0, ...,  0,  0,  0],
       [ 4,  0,  0, ...,  0,  0,  0]], dtype=uint8)

Normalize the Ratings Data matrix

In [146]:
normalised_matrix = ratings_mat - np.asarray([(np.mean(ratings_mat, 1))]).T
normalised_matrix

array([[ 3.16804636, -1.83195364, -1.83195364, ..., -1.83195364,
        -1.83195364,  1.16804636],
       [ 7.39884106, -1.60115894, -1.60115894, ..., -1.60115894,
        -1.60115894, -1.60115894],
       [12.82301325, -2.17698675, -2.17698675, ..., -2.17698675,
        -2.17698675, -2.17698675],
       ...,
       [ 4.50629139, -0.49370861, -0.49370861, ..., -0.49370861,
        -0.49370861, -0.49370861],
       [ 4.51655629, -0.48344371, -0.48344371, ..., -0.48344371,
        -0.48344371, -0.48344371],
       [ 3.31208609, -0.68791391, -0.68791391, ..., -0.68791391,
        -0.68791391, -0.68791391]])

Use the SVD function from numpy to perform SVD on the normalised ratings data matrix. Print the shapes of U, S, V matrices.

In [147]:
U,S,V = np.linalg.svd(normalised_matrix.T / np.sqrt(ratings_mat.shape[0] - 1))
U

array([[-3.49401661e-02,  5.09672206e-02,  2.20570773e-02, ...,
         5.36512681e-05,  2.95583589e-04,  2.41770455e-04],
       [ 2.75848796e-03,  1.30050399e-03,  1.57630915e-03, ...,
        -4.04481944e-03, -2.89470149e-03,  1.32583973e-03],
       [ 5.21311682e-03, -2.32200951e-04, -3.25017995e-04, ...,
         2.41427438e-03, -7.66514774e-03,  6.28207818e-03],
       ...,
       [ 5.22143789e-03, -2.84931289e-04, -8.36602606e-04, ...,
         8.55416003e-01, -8.06246598e-03,  2.06026092e-03],
       [ 5.18756772e-03, -2.13355438e-04, -3.97446178e-04, ...,
        -1.99833087e-02,  4.26475893e-01,  6.69475870e-03],
       [ 5.13763356e-03,  9.90961990e-05,  7.62074718e-04, ...,
         1.66101257e-03,  4.50606478e-03,  1.42144593e-01]])

Explain the differences between Cosine similarity and Euclidean distance. What are they and what do they do? Which one is better for movie recommendation and why?


When a pair of text similarities has a large difference in length but similar content, the Euclidean distance of them in the feature space is usually large if word frequency or word vector is used as the feature, while the angle between them may be small if cosine similarity is used, and thus the similarity is high. In addition, in the fields of text, image, video, etc., where the feature dimension of the object under study is often high, the cosine similarity still maintains the property of "1 when identical, 0 when orthogonal, and -1 when opposite" in the high-dimensional case, while the value of Euclidean distance is affected by the dimensionality, and the range is not fixed, and the meaning is also vague.

Euclidean distance between two points in Euclidean space is the length of a line segment between the two points. It can be calculated from the Cartesian coordinates of the points using the Pythagorean theorem. 

Cosine similarity between two vectors corresponds to their dot product divided by the product of their magnitudes.

Cosine similarity is better for movie recommendation. When two users have the same rating trend, but the rating values are very different, the cosine similarity tends to give a more optimal solution, but the solution given by the Euclidean distance is obviously not as reasonable as the cosine value.

In [148]:
def print_top5moivesrecommendations(movie_data, movie_id, top_indexes):
    print('top 5 movies that match a given a movie title are(total would be 6 if the given tilte was included):')
    for id in top_indexes + 1:
        print(movie_data[movie_data.movie_id == id].title.values[0])      
sliced = V[:,:] 

Based on cosine similarity and the matrix decomposition from SVD, sort the movies which are most similar and return the top 5 movies that match a given a movie title

In [149]:
# movie_id = int(input("Give a movie title"))
# for example, I choose No.1355(Nightwatch) to run the process
movie_id = 1355
print()
indexes = cosine_similarity(sliced, movie_id, 1+5)
print_top5moivesrecommendations(movies_data, movie_id, indexes)


top 5 movies that match a given a movie title are(total would be 6 if the given tilte was included):
Nightwatch (1997)
Blood & Wine (1997)
Nightmare on Elm Street, A (1984)
Omen, The (1976)
Transformers: The Movie, The (1986)
Young Guns II (1990)
